

name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: |
          sudo apt-get update
          sudo apt-get install cowsay
      - run: ls -l
      - run: cat README.md | --yes cowsay
      

